#!/bin/bash

assertFileExists() {
  if [ -f $1 -a -s $1 ]; then
    echo -e "\n $1 certificate/key file exists... OK"
  else
    echo -e "\n $1 certificate/key file NOT exists... FAIL"
    exit 1
  fi
}

assertFileNotExists() {
  if [ -f $1 -a -s $1 ]; then
    echo -e "\n $1 certificate/key file exists... FAIL"
    exit 1
  else
    echo -e "\n $1 certificate/key file NOT exists... OK"
  fi
}

testAllCertsExists() {
  echo -e "\nTest creating CA & SSL certs for dev env"
  export CREATE_SSL_CERTS="true"
  ./createCerts.sh
  assertFileExists "/etc/ssl/certs/server-ca-cert.crt"
  assertFileExists "/etc/ssl/certs/server-ca-key.key"
  assertFileExists "/etc/ssl/certs/server-ssl-csr.csr"
  assertFileExists "/etc/ssl/certs/server-ssl-key.key"
  assertFileExists "/etc/ssl/certs/server-ssl-cert.crt"
}

testOnlyCaCertsExists() {
  echo -e "\nTest creating CA certs for prod env"
  export CREATE_SSL_CERTS="false"
  /opt/kong/createCerts.sh
  assertFileExists "/etc/ssl/certs/server-ca-cert.crt"
  assertFileExists "/etc/ssl/certs/server-ca-key.key"
  assertFileNotExists "/etc/ssl/certs/server-ssl-csr.csr"
  assertFileNotExists "/etc/ssl/certs/server-ssl-key.key"
  assertFileNotExists "/etc/ssl/certs/server-ssl-cert.crt"
}

cp /opt/kong/dev.env /etc/ssl/.env
cd /opt/kong && rm -rf certs

case $1 in
  create_only_ca_certs)
    testOnlyCaCertsExists
  ;;
  create_all_certs)
    testAllCertsExists
  ;;
  all)
    testOnlyCaCertsExists
    testAllCertsExists
  ;;
esac
