#!/bin/bash

cd $(dirname $0)/../startup

docker container run \
  -v `pwd`:/app \
  -v `pwd`/../nginx/:/nginx_startup/ \
  --env BASE_HOST_DOMAIN=test-host-for-testing \
  --env HOST_SERVICE_SEPARATOR=-sepa- \
  --entrypoint /app/run_tests.sh \
  --rm -it $(docker build -q . )
