#!/bin/bash -u
result=0
test_index=0
error_index=0

show_binary_digits() {
  expansion=""
  total_tests=$(($test_index))
  for index in $(seq 1 $total_tests);
  do
    expansion="$expansion{0..1}"
  done
  expansion="($expansion)"
  eval "D2B=$expansion"
  echo ${D2B[$1]} | sed "s/1/*/g" | sed "s/0/-/g" | rev
}

assert_exit_code() {
  echo "Running $1..."
  ./$1
  if [[ $? -ne 0 ]]; then
    error_index=$((2 ** $test_index))
    result=$(($result + $error_index))
    echo "Failed running: $1"
  fi
  test_index=$(($test_index + 1))
}

show_results_and_exit() {
  if [[ $result -eq 0 ]]; then
    echo "All tests RAN OK."
  else
    echo "Some tests failed, exit code was: $result, failed tests: $(show_binary_digits $result)"
  fi
  exit $result
}
