#!/bin/bash

echo -e "\nChecking both checksums were computed..."

post_inst_checksums="/tmp/post-inst-plugins-checksum.chk"
pre_inst_checksums="/tmp/pre-inst-plugins-checksum.chk"

checkThatChecksumsDiffer() {
  echo -e "\nDeleting a plugin's file to generate checksum and validate it works..."
  rm /opt/kong/plugins/mtls_certs_manager/renew.lua
  /var/lib/dpkg/info/kong-docker-compose.postinst
  if cmp --silent -- "$post_inst_checksums" "$pre_inst_checksums"; then
      echo -e "\nChecksums were forced to differ but they are the same so restart would not be invoked... FAIL"
      exit 1
  else
      echo -e "\nChecksums are different when plugins are updated... OK"
      exit 0
  fi
}

checkThatChecksumsDiffer
