#!/bin/bash

src_root="$(dirname "$PWD")"

echo "Installing Docker-Compose"

curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

chmod +x /usr/local/bin/docker-compose

cd $src_root
echo "Pre-heating the DB to be available on all services"
timeout 40s docker-compose --env-file dev.env -f docker-compose.yml -f docker-compose.dev.yml -f admin_contract/docker-compose.contract.yml up kong-migrations kong-migrations-up
echo "Starting Kong Services..."
docker-compose --env-file dev.env -f docker-compose.yml -f docker-compose.dev.yml -f admin_contract/docker-compose.contract.yml up -d

echo "Running Contract Tests..."

docker run --env PYTHONUNBUFFERED=1 --env PACKAGE_VERSION --env PACT_BROKER_URL --env PACT_BROKER_USERNAME --env PACT_BROKER_PASSWORD --net="host" --add-host=admin.kong-server.com:127.0.0.1 --add-host=kong-direct-admin:127.0.0.1 ghcr.io/avature/kong-contract-tests:0.0.2

exit_code=$?

echo "Stopping Kong Services..."

docker-compose down

exit $exit_code
