version: '2.1'

services:
  kong:
    image: registry.xcade.net/kong-dev:${KONG_DOCKER_TAG}
    build:
        dockerfile: Dockerfile.kong
        context: ./
    extra_hosts:
      - "${SANDBOX_URL}:${SANDBOX_IP}"
