version: '3.1'

services:
  kong:
    extra_hosts:
      - "${SANDBOX_URL}:${SANDBOX_IP}"
  konga:
    volumes:
      - ./konga/kong_user.data:/run/kong_user.data:ro
    environment:
      KONGA_AUTH_PROVIDER: "local"
      KONGA_SEED_USER_DATA_SOURCE_FILE: /run/kong_user.data
  nginx:
    environment:
      CREATE_SSL_CERTS: "true"

