version: '3.1'

services:
  kong:
    image: "${KONG_DOCKER_IMAGE}${KONG_DOCKER_TAG}"
    build:
      context: ./kong
      args:
        KONG_DOCKER_TAG: $KONG_DOCKER_TAG
    extra_hosts:
      - "${SANDBOX_URL}:${SANDBOX_IP}"
    environment:
      HOST_SERVICE_SEPARATOR: "${HOST_SERVICE_SEPARATOR:-.}"
  konga:
    volumes:
      - ./konga/kong_user.data:/run/kong_user.data:ro
    environment:
      KONGA_AUTH_PROVIDER: "local"
      KONGA_SEED_USER_DATA_SOURCE_FILE: /run/kong_user.data
  startup:
    environment:
      CREATE_SSL_CERTS: "true"

