version: '3.1'

services:
  kong:
    extra_hosts:
      - "${SANDBOX_URL}:${SANDBOX_IP}"
  konga:
    volumes:
      - ./konga/kong_user.data:/run/kong_user.data:ro
  startup:
    environment:
      CREATE_SSL_CERTS: "true"

