#!/bin/bash -u

cd $(dirname $0)/test && . ./tests_helper

assert_exit_code "test_debian_install"
assert_exit_code "test_certificates create_only_ca_certs"
assert_exit_code "test_certificates create_all_certs"

show_results_and_exit
