#!/bin/bash

while IFS=$'\n' read line; do
  findargs+=('-not' '-path' "$line")
done < "./ignoredDirsAndFiles"

readarray filesPath < <(find . -type f "${findargs[@]}")
readarray installedFilesPath < <(find /opt/kong -type f)

for filePath in ${filesPath[@]}; do
  if [[ ! " ${installedFilesPath[@]} " =~ "/opt/kong/${filePath:2}" ]]; then
    notInstalledFiles+=(${filePath:2})
  fi
done

if [ ${#notInstalledFiles[@]} -ne 0 ]; then
  echo "The following files are missing from the debian install package file or need to be declared as ignored:"
  (IFS=$'\n'; echo "${notInstalledFiles[*]}")
  exit 1
else
  exit 0
fi
