#!/bin/bash -u

cd $(dirname $0)/test && . ./tests_helper

assert_exit_code "test_plugin mtls_certs_manager"
assert_exit_code "test_plugin client_consumer_validator"
assert_exit_code "test_plugin file_log_censored"
assert_exit_code "test_syntax"
assert_exit_code "test_startup"
assert_exit_code "test_kong_container"
# assert_exit_code "test_admin_api_contracts"

show_results_and_exit
