#!/bin/bash -u
result=0
test_index=0
error_index=0

show_binary_digits() {
  expansion=""
  total_tests=$(($test_index))
  for index in $(seq 1 $total_tests);
  do
    expansion="$expansion{0..1}"
  done
  expansion="($expansion)"
  eval "D2B=$expansion"
  echo ${D2B[$1]} | sed "s/1/*/g" | sed "s/0/-/g" | rev
}

assert_exit_code() {
  echo "Running $1..."
  ./$1
  if [[ $? -ne 0 ]]; then
    error_index=$((2 ** $test_index))
    result=$(($result + $error_index))
    echo "Failed running: $1"
  fi
  test_index=$(($test_index + 1))
}

show_results_and_exit() {
  if [[ $result -eq 0 ]]; then
    echo "All tests RAN OK."
  else
    echo "Some tests failed, exit code was: $result, failed tests: $(show_binary_digits $result)"
  fi
  exit $result
}

install_docker() {
  apt install -yq docker.io
  echo '{"bip": "192.168.43.1/24"}' > /etc/docker/daemon.json
  systemctl restart docker
}

if [[ "$USER" == "root" ]]; then
  install_docker
fi

assert_exit_code "test_plugin mtls_certs_manager"
assert_exit_code "test_plugin client_consumer_validator"
assert_exit_code "test_plugin file_log_censored"
assert_exit_code "test_syntax"
assert_exit_code "test_startup"

show_results_and_exit
