#!/usr/bin/dh-exec
## Indicate where your files will be deployed
## eg:
## bin/compiled => /opt/project/run
## config/config.production.toml => /etc/project/config.toml
.env.example => opt/kong/.env
secrets.ini.example => opt/kong/secrets.ini
docker-compose.yml opt/kong
{start,stop}.sh opt/kong
startKongBash.sh opt/kong
kong/connectToDB.sh opt/kong/kong
konga/connectToDB.sh opt/kong/konga
konga/kong_node.data opt/kong/konga
