#!/usr/bin/dh-exec
## Indicate where your files will be deployed
## eg:
## bin/compiled => /opt/project/run
## config/config.production.toml => /etc/project/config.toml
.env.example => opt/kong/.env
docker-compose.yml opt/kong
stop.sh opt/kong
start.sh opt/kong
startKongBash.sh opt/kong
createDevCerts.sh opt/kong
createCerts.sh opt/kong
kong/connectToDB.sh opt/kong/kong
konga/connectToDB.sh opt/kong/konga
konga/kong_node.data opt/kong/konga
startup/createAdmin.py opt/kong/startup
startup/init.sh opt/kong/startup
startup/requirements.txt opt/kong/startup
startup/fixture.py opt/kong/startup
startup/config.py opt/kong/startup
nginx/sslCertificates.conf opt/kong/nginx
nginx/konga.conf opt/kong/nginx
nginx/gateway.conf opt/kong/nginx
nginx/admin.conf opt/kong/nginx
nginx/server_hosts/konga-url.conf.template opt/kong/nginx/server_hosts
nginx/server_hosts/gateway-url.conf.template opt/kong/nginx/server_hosts
nginx/server_hosts/admin-url.conf.template opt/kong/nginx/server_hosts
nginx/server_hosts/create-urls.sh opt/kong/nginx/server_hosts
kong/conf/custom-nginx.conf opt/kong/kong/conf
kong/conf/custom-entrypoint.sh opt/kong/kong/conf
kong/conf/kong.conf opt/kong/kong/conf
plugins/mtls_certs_manager/register.lua opt/kong/plugins/mtls_certs_manager
plugins/mtls_certs_manager/renew.lua opt/kong/plugins/mtls_certs_manager
plugins/mtls_certs_manager/base.lua opt/kong/plugins/mtls_certs_manager
plugins/mtls_certs_manager/factory.lua opt/kong/plugins/mtls_certs_manager
plugins/mtls_certs_manager/handler.lua opt/kong/plugins/mtls_certs_manager
plugins/mtls_certs_manager/schema.lua opt/kong/plugins/mtls_certs_manager
plugins/mtls_certs_manager/x509_name_helper.lua opt/kong/plugins/mtls_certs_manager
plugins/client_consumer_validator/schema.lua opt/kong/plugins/client_consumer_validator
plugins/client_consumer_validator/access.lua opt/kong/plugins/client_consumer_validator
plugins/client_consumer_validator/handler.lua opt/kong/plugins/client_consumer_validator
plugins/file_log_censored/schema.lua opt/kong/plugins/file_log_censored
plugins/file_log_censored/handler.lua opt/kong/plugins/file_log_censored
plugins/file_log_censored/attribute_remover.lua opt/kong/plugins/file_log_censored
