#!/bin/bash

# . $(dirname $0)/plugins_reload_helper

pre_inst_checksums="/tmp/pre-inst-plugins-checksum.chk"
post_inst_checksums="/tmp/post-inst-plugins-checksum.chk"

generatePluginsChecksums() {
    find /opt/kong/plugins -print0 2>/dev/null -type f -exec sha1sum "{}" + > $1
}

generatePluginsChecksums $post_inst_checksums

if cmp --silent -- "$post_inst_checksums" "$pre_inst_checksums"; then
  echo "Previous plugin files are identical to the new ones, avoiding restart"
else
  echo "New Plugins were installed, restarting kong"
  cd /opt/kong
  docker-compose restart kong
fi
