#!/bin/bash

pre_inst_plugins_checksums="/tmp/pre-inst-plugins-checksum.chk"
post_inst_plugins_checksums="/tmp/post-inst-plugins-checksum.chk"
pre_inst_nginx_checksums="/tmp/pre-inst-nginx-checksum.chk"
post_inst_nginx_checksums="/tmp/post-inst-nginx-checksum.chk"
plugins_path="/opt/kong/plugins"
nginx_path="/opt/kong/nginx"

runPostInstChecksums() {
    echo -e "\nGenerating post-install checksums into file $2"
    find $1 -print0 2>/dev/null -type f -name $3 -exec sha1sum "{}" + > "$2"
}

assertIsInstalledAndExitIfNeeded() {
    which $1
    if [[ $? -eq 0 ]]; then
        $3
    else
        echo -e "\n$1 isn't installed cannot restart $2"
        current_time=$(date "+%Y.%m.%d-%H.%M.%S")
        echo "$2 is pending to be restarted because it changed - $current_time" > "/opt/kong/$2-pending-restart.log"
    fi
}

restartKongIfNeeded() {
    if [[ `docker-compose ps --services --filter "status=running" | grep kong` ]]; then
        docker-compose restart kong
    else
        echo "Kong service is not running. Restart was skipped."
    fi
}

restartNginxIfNeeded() {
    if [[ `docker-compose ps --services --filter "status=running" | grep nginx` ]]; then
        docker-compose exec nginx nginx -s reload
    else
        echo "Nginx service is not running. Restart was skipped."
    fi
}

compareChecksumsAndRestartIfneeded() {
    if cmp --silent -- "$1" "$2"; then
        echo "Previous $4 files are identical to the new ones, avoiding restart"
    else
        echo "$4 files were updated/installed, restarting $4"
        cd /opt/kong
        if [ -n "$5" ]; then
            assertIsInstalledAndExitIfNeeded "$3" "$4" $5
        fi
    fi
}

runPostInstChecksums $plugins_path $post_inst_plugins_checksums "*.lua"
runPostInstChecksums $nginx_path $post_inst_nginx_checksums "*.conf"
compareChecksumsAndRestartIfneeded $post_inst_plugins_checksums $pre_inst_plugins_checksums "docker-compose" "kong" restartKongIfNeeded
compareChecksumsAndRestartIfneeded $post_inst_nginx_checksums $pre_inst_nginx_checksums "nginx" "nginx"
restartNginxIfNeeded
