#!/bin/bash

# FIXME:
# This logic is shared with postinst also so the ideal would be to have a separate file plugins_checksum_helper
# library all call it from both pre and post inst but there's no easy way to do this because the DPMS only decompress preinst
# One option would be to include that library embedded on this file and decompress it to somewhere usable by both
# https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html#summary-of-ways-maintainer-scripts-are-called

pre_inst_checksums="/tmp/pre-inst-plugins-checksum.chk"
post_inst_checksums="/tmp/post-inst-plugins-checksum.chk"

generatePluginsChecksums() {
    find /opt/kong/plugins -print0 2>/dev/null -type f -exec sha1sum "{}" + > $1
}

generatePreInstChecksums() {
    echo -e "\nGenerating pre-install checksums..."
    generatePluginsChecksums $pre_inst_checksums
    exit 0;
}

generatePostInstChecksums() {
    echo -e "\nGenerating post-install checksums..."
    generatePluginsChecksums $post_inst_checksums
}

if [ "$1" = "postinst" ]
then
    generatePostInstChecksums
else
    generatePreInstChecksums
fi
