---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-kong-pvc
  namespace: customendpoints-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs-replica-3
