apiVersion: apps/v1
kind: Deployment
metadata:
  name: konga-ui
  namespace: customendpoints-dev
  annotations:
    avature.net/team: customendpoints
    avature.net/environment: Development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: konga-ui
  template:
    metadata:
      labels:
        app: konga-ui
    spec:
      containers:
        - name: konga-ui
          image: pantsel/konga:next
          env:
            - name: DB_HOST
              value: 'db-svc'
            - name: DB_PORT
              value: '5432'
            - name: DB_USER
              value: pguser
            - name: DB_PASSWORD
              value: password
            - name: TOKEN_SECRET
              value: km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
            - name: DB_DATABASE
              value: konga_db
          ports:
          - containerPort: 1337
---
apiVersion: v1
kind: Service
metadata:
  name: konga-ui-svc
spec:
  selector:
    app: konga-ui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 1337
