apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-gateway-deploy
  namespace: customendpoints-dev
  annotations:
    avature.net/team: customendpoints
    avature.net/environment: Development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kong-gateway
  template:
    metadata:
      labels:
        app: kong-gateway
    spec:
      containers:
        - name: kong-gateway
          image: kong:2.1.4
          env:
            - name: KONG_ADMIN_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_ADMIN_ERROR_LOG
              value: /dev/stderr
            - name: KONG_ADMIN_LISTEN
              value: '0.0.0.0:8001'
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_DATABASE
              value: 'kong'
            - name: KONG_PG_HOST
              value: 'db-svc'
            - name: KONG_PG_PORT
              value: '5432'
            - name: KONG_PG_PASSWORD
              value: password
            - name: KONG_PG_USER
              value: pguser
            - name: KONG_PROXY_ACCESS_LOG
              value: /dev/stdout
            - name: KONG_PROXY_ERROR_LOG
              value: /dev/stderr
          ports:
          - containerPort: 8000
          - containerPort: 8001
      initContainers:
        - name: kong-migrations
          image: kong:2.1.4
          command: ['kong', 'migrations', 'bootstrap']
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_DATABASE
              value: 'kong'
            - name: KONG_PG_HOST
              value: 'db-svc'
            - name: KONG_PG_PORT
              value: '5432'
            - name: KONG_PG_PASSWORD
              value: password
            - name: KONG_PG_USER
              value: pguser
        - name: kong-migrations-up
          image: kong:2.1.4
          command: ['kong', 'migrations', 'up']
          env:
            - name: KONG_DATABASE
              value: postgres
            - name: KONG_PG_DATABASE
              value: 'kong'
            - name: KONG_PG_HOST
              value: 'db-svc'
            - name: KONG_PG_PORT
              value: '5432'
            - name: KONG_PG_PASSWORD
              value: password
            - name: KONG_PG_USER
              value: pguser
---
apiVersion: v1
kind: Service
metadata:
  name: kong-svc
spec:
  selector:
    app: kong-gateway
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: gateway-endpoint
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: admin-endpoint
